
    hold off
    newplot
    xlabel('x')
    ylabel('y')
    zlabel('z')
    DrawAllJoints(1);
    h(1) = DrawMarker([com(1),com(2),0]','b'); % com
    h(2) = DrawMarker([zmpx,zmpy,zmpz]','r'); % zmp
    legend(h,'CoM','ZMP');
    axis equal
    set(gca,...
        'CameraPositionMode','manual',...
        'CameraPosition',[4,4,2],...
        'CameraViewAngleMode','manual',....
        'CameraViewAngle',0,...
        'Projection','perspective',...
        'XLimMode','manual',...
        'XLim',[-0.5 0.5],...
        'YLimMode','manual',...
        'YLim',[-0.5 0.5],...
        'ZLimMode','manual',...
        'ZLim',[-0 0.75])
    grid on
    text(0.5, -0.4, .5, ['time=',num2str(time(k),'%5.3f')])
%     set(gcf,'Position',[2000 00 400 300]) % plot on 2nd screen
    drawnow;